const SENTENCE_IPA = {
  "The sun rises while I eat breakfast.": "ðə sʌn raɪzəz waɪl aɪ it brɛkfəst",
  "Yesterday, I arose early for school.": "jɛstɚdeɪ aɪ ɚoʊz ɝli fɔr skul",
  "I've arisen early for school.": "aɪv ɚɪzən ɝli fɔr skul",
  "I wake up before my alarm goes off.": "aɪ weɪk ʌp bɪfɔr maɪ əlɑrm ɡoʊz ɔf",
  "Yesterday, I woke up before my alarm went off.": "jɛstɚdeɪ aɪ woʊk ʌp bɪfɔr maɪ əlɑrm wɛnt ɔf",
  "I've woken up before my alarm many times.": "aɪv woʊkən ʌp bɪfɔr maɪ əlɑrm mɛni taɪmz",
  "I am kind to my friends.": "aɪ æm kaɪnd tu maɪ frɛndz",
  "Yesterday, I was kind to my friend.": "jɛstɚdeɪ aɪ wɑz kaɪnd tu maɪ frɛnd",
  "I've been kind to my friend.": "aɪv bɪn kaɪnd tu maɪ frɛnd",
  "My backpack is easy to bear.": "maɪ bækpæk ɪz izi tu bɛr",
  "Yesterday, I bore my heavy school bag.": "jɛstɚdeɪ aɪ bɔr maɪ hɛvi skul bæɡ",
  "I've borne my heavy school bag.": "aɪv bɔrn maɪ hɛvi skul bæɡ",
  "My drum beats loudly in music class.": "maɪ drʌm bits laʊdli ɪn mjuzɪk klæs",
  "Yesterday, I beat my brother at a board game.": "jɛstɚdeɪ aɪ bit maɪ brʌðɚ æt ə bɔrd ɡeɪm",
  "I've beaten my brother at a board game.": "aɪv bitən maɪ brʌðɚ æt ə bɔrd ɡeɪm",
  "My plant becomes taller each week.": "maɪ plænt bɪkʌmz tɔlɚ itʃ wik",
  "Yesterday, I became taller this year.": "jɛstɚdeɪ aɪ bɪkeɪm tɔlɚ ðɪs jɪr",
  "I've become taller this year.": "aɪv bɪkʌm tɔlɚ ðɪs jɪr",
  "Our class begins after the bell rings.": "aʊɚ klæs bɪɡɪnz æftɚ ðə bɛl rɪŋz",
  "Yesterday, I began my homework after dinner.": "jɛstɚdeɪ aɪ bɪɡæn maɪ hoʊmwɝk æftɚ dɪnɚ",
  "I've begun my homework after dinner.": "aɪv bɪɡʌn maɪ hoʊmwɝk æftɚ dɪnɚ",
  "A paper clip bends easily.": "ə peɪpɚ klɪp bɛndz izəli",
  "Yesterday, I bent a paper clip.": "jɛstɚdeɪ aɪ bɛnt ə peɪpɚ klɪp",
  "I've bent a paper clip.": "aɪv bɛnt ə peɪpɚ klɪp",
  "I bet on the color of a car.": "aɪ bɛt ɑn ðə kʌlɚ ʌv ə kɑr",
  "Yesterday, I bet on the color of a car.": "jɛstɚdeɪ aɪ bɛt ɑn ðə kʌlɚ ʌv ə kɑr",
  "I've bet on the color of a car.": "aɪv bɛt ɑn ðə kʌlɚ ʌv ə kɑr",
  "I bid for a toy at the school auction.": "aɪ bɪd fɔr ə tɔɪ æt ðə skul ɑkʃən",
  "Yesterday, I bid for a toy at the school auction.": "jɛstɚdeɪ aɪ bɪd fɔr ə tɔɪ æt ðə skul ɑkʃən",
  "I've bid for a toy at the school auction.": "aɪv bɪd fɔr ə tɔɪ æt ðə skul ɑkʃən",
  "I bind my books with a ribbon.": "aɪ baɪnd maɪ bʊks wɪð ə rɪbən",
  "Yesterday, I bound my books with a ribbon.": "jɛstɚdeɪ aɪ baʊnd maɪ bʊks wɪð ə rɪbən",
  "I've bound my books with a ribbon.": "aɪv baʊnd maɪ bʊks wɪð ə rɪbən",
  "A puppy bites a chewy toy.": "ə pʌpi baɪts ə tʃui tɔɪ",
  "Yesterday, I bit an apple at lunch.": "jɛstɚdeɪ aɪ bɪt æn æpəl æt lʌntʃ",
  "I've bitten an apple at lunch.": "aɪv bɪtən æn æpəl æt lʌntʃ",
  "My scraped knee bleeds a little.": "maɪ skreɪpt ni blidz ə lɪtəl",
  "Yesterday, I bled a little after a scraped knee.": "jɛstɚdeɪ aɪ blɛd ə lɪtəl æftɚ ə skreɪpt ni",
  "I've bled a little after a scraped knee.": "aɪv blɛd ə lɪtəl æftɚ ə skreɪpt ni",
  "The wind blows bubbles across the yard.": "ðə waɪnd bloʊz bʌbəlz əkrɔs ðə jɑrd",
  "Yesterday, I blew bubbles through a straw.": "jɛstɚdeɪ aɪ blu bʌbəlz θru ə strɔ",
  "I've blown bubbles through a straw.": "aɪv bloʊn bʌbəlz θru ə strɔ",
  "A dry twig breaks under my shoe.": "ə draɪ twɪɡ breɪks ʌndɚ maɪ ʃu",
  "Yesterday, I broke a dry twig.": "jɛstɚdeɪ aɪ broʊk ə draɪ twɪɡ",
  "I've broken a dry twig.": "aɪv broʊkən ə draɪ twɪɡ",
  "I breed baby fish in a game.": "aɪ brid beɪbi fɪʃ ɪn ə ɡeɪm",
  "Yesterday, I bred baby fish in a game.": "jɛstɚdeɪ aɪ brɛd beɪbi fɪʃ ɪn ə ɡeɪm",
  "I've bred baby fish in a game.": "aɪv brɛd beɪbi fɪʃ ɪn ə ɡeɪm",
  "My mom brings snacks for our picnic.": "maɪ mɑm brɪŋz snæks fɔr aʊɚ pɪknɪk",
  "Yesterday, I brought my lunch box to school.": "jɛstɚdeɪ aɪ brɔt maɪ lʌntʃ bɑks tu skul",
  "I've brought my lunch box to school.": "aɪv brɔt maɪ lʌntʃ bɑks tu skul",
  "I broadcast the class news.": "aɪ brɔdkæst ðə klæs nuz",
  "Yesterday, I broadcast the class news.": "jɛstɚdeɪ aɪ brɔdkæst ðə klæs nuz",
  "I've broadcast the class news.": "aɪv brɔdkæst ðə klæs nuz",
  "I build a block tower.": "aɪ bɪld ə blɑk taʊɚ",
  "Yesterday, I built a block tower.": "jɛstɚdeɪ aɪ bɪlt ə blɑk taʊɚ",
  "I've built a block tower.": "aɪv bɪlt ə blɑk taʊɚ",
  "I burn toast for breakfast.": "aɪ bɝn toʊst fɔr brɛkfəst",
  "Yesterday, I burned toast for breakfast.": "jɛstɚdeɪ aɪ bɝnd toʊst fɔr brɛkfəst",
  "I've burned toast for breakfast.": "aɪv bɝnd toʊst fɔr brɛkfəst",
  "A balloon bursts when I sit on it.": "ə bəlun bɝsts wɛn aɪ sɪt ɑn ɪt",
  "Yesterday, I burst a balloon by accident.": "jɛstɚdeɪ aɪ bɝst ə bəlun baɪ æksədənt",
  "I've burst a balloon by accident.": "aɪv bɝst ə bəlun baɪ æksədənt",
  "I buy a snack at the school fair.": "aɪ baɪ ə snæk æt ðə skul fɛr",
  "Yesterday, I bought a snack at the school fair.": "jɛstɚdeɪ aɪ bɑt ə snæk æt ðə skul fɛr",
  "I've bought a snack at the school fair.": "aɪv bɑt ə snæk æt ðə skul fɛr",
  "I catch a ball with my friend.": "aɪ kætʃ ə bɔl wɪð maɪ frɛnd",
  "Yesterday, I caught a ball with my friend.": "jɛstɚdeɪ aɪ kɑt ə bɔl wɪð maɪ frɛnd",
  "I've caught a ball with my friend.": "aɪv kɑt ə bɔl wɪð maɪ frɛnd",
  "I choose a book from the library.": "aɪ tʃuz ə bʊk frʌm ðə laɪbrɛri",
  "Yesterday, I chose a book from the library.": "jɛstɚdeɪ aɪ tʃoʊz ə bʊk frʌm ðə laɪbrɛri",
  "I've chosen a book from the library.": "aɪv tʃoʊzən ə bʊk frʌm ðə laɪbrɛri",
  "My friend comes over after school.": "maɪ frɛnd kʌmz oʊvɚ æftɚ skul",
  "Yesterday, I came home from school.": "jɛstɚdeɪ aɪ keɪm hoʊm frʌm skul",
  "I've come home from school.": "aɪv kʌm hoʊm frʌm skul",
  "This snack costs five dollars.": "ðɪs snæk kɑsts faɪv dɑlɚz",
  "Yesterday, this snack cost five dollars.": "jɛstɚdeɪ ðɪs snæk kɑst faɪv dɑlɚz",
  "This snack has cost five dollars all week.": "ðɪs snæk hæz kɑst faɪv dɑlɚz ɔl wik",
  "A snail creeps along the garden wall.": "ə sneɪl krips əlɔŋ ðə ɡɑrdən wɔl",
  "Yesterday, I crept quietly to the kitchen.": "jɛstɚdeɪ aɪ krɛpt kwaɪətli tu ðə kɪtʃən",
  "I've crept quietly to the kitchen.": "aɪv krɛpt kwaɪətli tu ðə kɪtʃən",
  "I cut paper for an art project.": "aɪ kʌt peɪpɚ fɔr æn ɑrt prɑdʒɛkt",
  "Yesterday, I cut paper for an art project.": "jɛstɚdeɪ aɪ kʌt peɪpɚ fɔr æn ɑrt prɑdʒɛkt",
  "I've cut paper for an art project.": "aɪv kʌt peɪpɚ fɔr æn ɑrt prɑdʒɛkt",
  "I dig a hole in the sand.": "aɪ dɪɡ ə hoʊl ɪn ðə sænd",
  "Yesterday, I dug a hole in the sand.": "jɛstɚdeɪ aɪ dʌɡ ə hoʊl ɪn ðə sænd",
  "I've dug a hole in the sand.": "aɪv dʌɡ ə hoʊl ɪn ðə sænd",
  "I do my homework after dinner.": "aɪ du maɪ hoʊmwɝk æftɚ dɪnɚ",
  "Yesterday, I did my homework after dinner.": "jɛstɚdeɪ aɪ dɪd maɪ hoʊmwɝk æftɚ dɪnɚ",
  "I've done my homework after dinner.": "aɪv dʌn maɪ hoʊmwɝk æftɚ dɪnɚ",
  "I draw a picture of my pet.": "aɪ drɔ ə pɪktʃɚ ʌv maɪ pɛt",
  "Yesterday, I drew a picture of my pet.": "jɛstɚdeɪ aɪ dru ə pɪktʃɚ ʌv maɪ pɛt",
  "I've drawn a picture of my pet.": "aɪv drɔn ə pɪktʃɚ ʌv maɪ pɛt",
  "I dream about a fun trip.": "aɪ drim əbaʊt ə fʌn trɪp",
  "Yesterday, I dreamed about a fun trip.": "jɛstɚdeɪ aɪ drimd əbaʊt ə fʌn trɪp",
  "I've dreamed about a fun trip.": "aɪv drimd əbaʊt ə fʌn trɪp",
  "I drink milk with breakfast.": "aɪ drɪŋk mɪlk wɪð brɛkfəst",
  "Yesterday, I drank milk with breakfast.": "jɛstɚdeɪ aɪ dræŋk mɪlk wɪð brɛkfəst",
  "I've drunk milk with breakfast.": "aɪv drʌŋk mɪlk wɪð brɛkfəst",
  "My dad drives us to the pool.": "maɪ dæd draɪvz ʌs tu ðə pul",
  "Yesterday, I drove a toy car on the floor.": "jɛstɚdeɪ aɪ droʊv ə tɔɪ kɑr ɑn ðə flɔr",
  "I've driven a toy car on the floor.": "aɪv drɪvən ə tɔɪ kɑr ɑn ðə flɔr",
  "I eat an apple for a snack.": "aɪ it æn æpəl fɔr ə snæk",
  "Yesterday, I ate an apple for a snack.": "jɛstɚdeɪ aɪ eɪt æn æpəl fɔr ə snæk",
  "I've eaten an apple for a snack.": "aɪv itən æn æpəl fɔr ə snæk",
  "My ball falls behind the sofa.": "maɪ bɔl fɔlz bɪhaɪnd ðə soʊfə",
  "Yesterday, I fell off my bike.": "jɛstɚdeɪ aɪ fɛl ɔf maɪ baɪk",
  "I've fallen off my bike.": "aɪv fɑlən ɔf maɪ baɪk",
  "I feed my goldfish.": "aɪ fid maɪ ɡoʊldfɪʃ",
  "Yesterday, I fed my goldfish.": "jɛstɚdeɪ aɪ fɛd maɪ ɡoʊldfɪʃ",
  "I've fed my goldfish.": "aɪv fɛd maɪ ɡoʊldfɪʃ",
  "I feel happy at the park.": "aɪ fil hæpi æt ðə pɑrk",
  "Yesterday, I felt happy at the park.": "jɛstɚdeɪ aɪ fɛlt hæpi æt ðə pɑrk",
  "I've felt happy at the park.": "aɪv fɛlt hæpi æt ðə pɑrk",
  "I fight a monster in my game.": "aɪ faɪt ə mɑnstɚ ɪn maɪ ɡeɪm",
  "Yesterday, I fought a monster in my game.": "jɛstɚdeɪ aɪ fɔt ə mɑnstɚ ɪn maɪ ɡeɪm",
  "I've fought a monster in my game.": "aɪv fɔt ə mɑnstɚ ɪn maɪ ɡeɪm",
  "I find my missing pencil.": "aɪ faɪnd maɪ mɪsɪŋ pɛnsəl",
  "Yesterday, I found my missing pencil.": "jɛstɚdeɪ aɪ faʊnd maɪ mɪsɪŋ pɛnsəl",
  "I've found my missing pencil.": "aɪv faʊnd maɪ mɪsɪŋ pɛnsəl",
  "My new shirt fits me well.": "maɪ nu ʃɝt fɪts mi wɛl",
  "Yesterday, my new shirt fit me well.": "jɛstɚdeɪ maɪ nu ʃɝt fɪt mi wɛl",
  "My new shirt has fit me all year.": "maɪ nu ʃɝt hæz fɪt mi ɔl jɪr",
  "A squirrel flees when our dog barks.": "ə skwɝəl fliz wɛn aʊɚ dɔɡ bɑrks",
  "Yesterday, I fled from a scary movie scene.": "jɛstɚdeɪ aɪ flɛd frʌm ə skɛri muvi sin",
  "I've fled from a scary movie scene.": "aɪv flɛd frʌm ə skɛri muvi sin",
  "I fling my backpack onto the chair.": "aɪ flɪŋ maɪ bækpæk ɑntu ðə tʃɛr",
  "Yesterday, I flung my backpack onto the chair.": "jɛstɚdeɪ aɪ flʌŋ maɪ bækpæk ɑntu ðə tʃɛr",
  "I've flung my backpack onto the chair.": "aɪv flʌŋ maɪ bækpæk ɑntu ðə tʃɛr",
  "A bird flies over the playground.": "ə bɝd flaɪz oʊvɚ ðə pleɪɡraʊnd",
  "Yesterday, I flew a kite at the beach.": "jɛstɚdeɪ aɪ flu ə kaɪt æt ðə bitʃ",
  "I've flown a kite at the beach.": "aɪv floʊn ə kaɪt æt ðə bitʃ",
  "My dad forbids candy before dinner.": "maɪ dæd fɚbɪdz kændi bɪfɔr dɪnɚ",
  "Yesterday, my dad forbade candy before dinner.": "jɛstɚdeɪ maɪ dæd fɚbeɪd kændi bɪfɔr dɪnɚ",
  "My dad has forbidden candy before dinner.": "maɪ dæd hæz fɔrbɪdən kændi bɪfɔr dɪnɚ",
  "The weather app forecasts rain tomorrow.": "ðə wɛðɚ æp fɔrkæsts reɪn təmɑroʊ",
  "Yesterday, the weather app forecast rain.": "jɛstɚdeɪ ðə wɛðɚ æp fɔrkæst reɪn",
  "The weather app has forecast rain for tomorrow.": "ðə wɛðɚ æp hæz fɔrkæst reɪn fɔr təmɑroʊ",
  "I forget my lunch box at school.": "aɪ fɚɡɛt maɪ lʌntʃ bɑks æt skul",
  "Yesterday, I forgot my lunch box at school.": "jɛstɚdeɪ aɪ fɚɡɑt maɪ lʌntʃ bɑks æt skul",
  "I've forgotten my lunch box at school.": "aɪv fɚɡɑtən maɪ lʌntʃ bɑks æt skul",
  "The story foretells a surprise ending.": "ðə stɔri fɔrtɛlz ə sɚpraɪz ɛndɪŋ",
  "The story foretold a surprise ending.": "ðə stɔri fɔrtoʊld ə sɚpraɪz ɛndɪŋ",
  "The story has foretold a surprise ending.": "ðə stɔri hæz fɔrtoʊld ə sɚpraɪz ɛndɪŋ",
  "I forgive my friend for a small mistake.": "aɪ fɚɡɪv maɪ frɛnd fɔr ə smɔl mɪsteɪk",
  "Yesterday, I forgave my friend for a small mistake.": "jɛstɚdeɪ aɪ fɚɡeɪv maɪ frɛnd fɔr ə smɔl mɪsteɪk",
  "I've forgiven my friend for a small mistake.": "aɪv fɚɡɪvən maɪ frɛnd fɔr ə smɔl mɪsteɪk",
  "I forsake my old teddy bear.": "aɪ fɔrseɪk maɪ oʊld tɛdi bɛr",
  "Yesterday, I forsook my old teddy bear.": "jɛstɚdeɪ aɪ fɔrsʊk maɪ oʊld tɛdi bɛr",
  "I've forsaken my old teddy bear.": "aɪv fɔrseɪkən maɪ oʊld tɛdi bɛr",
  "Water freezes in my ice tray.": "wɔtɚ frizɪz ɪn maɪ aɪs treɪ",
  "Yesterday, I froze juice for a popsicle.": "jɛstɚdeɪ aɪ froʊz dʒus fɔr ə pɑpsɪkəl",
  "I've frozen juice for a popsicle.": "aɪv froʊzən dʒus fɔr ə pɑpsɪkəl",
  "I get a sticker from my teacher.": "aɪ ɡɛt ə stɪkɚ frʌm maɪ titʃɚ",
  "Yesterday, I got a sticker from my teacher.": "jɛstɚdeɪ aɪ ɡɑt ə stɪkɚ frʌm maɪ titʃɚ",
  "I've gotten a sticker from my teacher.": "aɪv ɡɑtən ə stɪkɚ frʌm maɪ titʃɚ",
  "I give my friend a turn.": "aɪ ɡɪv maɪ frɛnd ə tɝn",
  "Yesterday, I gave my friend a turn.": "jɛstɚdeɪ aɪ ɡeɪv maɪ frɛnd ə tɝn",
  "I've given my friend a turn.": "aɪv ɡɪvən maɪ frɛnd ə tɝn",
  "My family goes to the park on Sundays.": "maɪ fæməli ɡoʊz tu ðə pɑrk ɑn sʌndeɪz",
  "Yesterday, I went to the playground.": "jɛstɚdeɪ aɪ wɛnt tu ðə pleɪɡraʊnd",
  "I've gone to the playground.": "aɪv ɡɔn tu ðə pleɪɡraʊnd",
  "I grind cookies for my family.": "aɪ ɡraɪnd kʊkiz fɔr maɪ fæməli",
  "Yesterday, I ground cookies for my family.": "jɛstɚdeɪ aɪ ɡraʊnd kʊkiz fɔr maɪ fæməli",
  "I've ground cookies for my family.": "aɪv ɡraʊnd kʊkiz fɔr maɪ fæməli",
  "My bean plant grows by the window.": "maɪ bin plænt ɡroʊz baɪ ðə wɪndoʊ",
  "Yesterday, I grew a bean plant in class.": "jɛstɚdeɪ aɪ ɡru ə bin plænt ɪn klæs",
  "I've grown a bean plant in class.": "aɪv ɡroʊn ə bin plænt ɪn klæs",
  "My jacket hangs by the front door.": "maɪ dʒækət hæŋz baɪ ðə frʌnt dɔr",
  "Yesterday, I hung my jacket by the door.": "jɛstɚdeɪ aɪ hʌŋ maɪ dʒækət baɪ ðə dɔr",
  "I've hung my jacket by the door.": "aɪv hʌŋ maɪ dʒækət baɪ ðə dɔr",
  "I have a snack after school.": "aɪ hæv ə snæk æftɚ skul",
  "Yesterday, I had a snack after school.": "jɛstɚdeɪ aɪ hæd ə snæk æftɚ skul",
  "I've had a snack after school.": "aɪv hæd ə snæk æftɚ skul",
  "I hear the school bell.": "aɪ hir ðə skul bɛl",
  "Yesterday, I heard the school bell.": "jɛstɚdeɪ aɪ hɝd ðə skul bɛl",
  "I've heard the school bell.": "aɪv hɝd ðə skul bɛl",
  "I hide behind the sofa.": "aɪ haɪd bɪhaɪnd ðə soʊfə",
  "Yesterday, I hid behind the sofa.": "jɛstɚdeɪ aɪ hɪd bɪhaɪnd ðə soʊfə",
  "I've hidden behind the sofa.": "aɪv hɪdən bɪhaɪnd ðə soʊfə",
  "I hit a baseball with my bat.": "aɪ hɪt ə beɪsbɔl wɪð maɪ bæt",
  "Yesterday, I hit a baseball with my bat.": "jɛstɚdeɪ aɪ hɪt ə beɪsbɔl wɪð maɪ bæt",
  "I've hit a baseball with my bat.": "aɪv hɪt ə beɪsbɔl wɪð maɪ bæt",
  "I hold my mom's hand.": "aɪ hoʊld maɪ mɑmz hænd",
  "Yesterday, I held my mom's hand.": "jɛstɚdeɪ aɪ hɛld maɪ mɑmz hænd",
  "I've held my mom's hand.": "aɪv hɛld maɪ mɑmz hænd",
  "I hurt my knee while playing.": "aɪ hɝt maɪ ni waɪl pleɪɪŋ",
  "Yesterday, I hurt my knee while playing.": "jɛstɚdeɪ aɪ hɝt maɪ ni waɪl pleɪɪŋ",
  "I've hurt my knee while playing.": "aɪv hɝt maɪ ni waɪl pleɪɪŋ",
  "I keep my crayons in a box.": "aɪ kip maɪ kreɪɑnz ɪn ə bɑks",
  "Yesterday, I kept my crayons in a box.": "jɛstɚdeɪ aɪ kɛpt maɪ kreɪɑnz ɪn ə bɑks",
  "I've kept my crayons in a box.": "aɪv kɛpt maɪ kreɪɑnz ɪn ə bɑks",
  "I kneel beside my bed.": "aɪ nil bɪsaɪd maɪ bɛd",
  "Yesterday, I kneeled beside my bed.": "jɛstɚdeɪ aɪ nild bɪsaɪd maɪ bɛd",
  "I've kneeled beside my bed.": "aɪv nild bɪsaɪd maɪ bɛd",
  "I know the answer to the question.": "aɪ noʊ ðə ænsɚ tu ðə kwɛstʃən",
  "Yesterday, I knew the answer to the question.": "jɛstɚdeɪ aɪ nu ðə ænsɚ tu ðə kwɛstʃən",
  "I've known the answer to the question.": "aɪv noʊn ðə ænsɚ tu ðə kwɛstʃən",
  "I lay my book on the table.": "aɪ leɪ maɪ bʊk ɑn ðə teɪbəl",
  "Yesterday, I laid my book on the table.": "jɛstɚdeɪ aɪ leɪd maɪ bʊk ɑn ðə teɪbəl",
  "I've laid my book on the table.": "aɪv leɪd maɪ bʊk ɑn ðə teɪbəl",
  "My teacher leads us to the library.": "maɪ titʃɚ lidz ʌs tu ðə laɪbrɛri",
  "Yesterday, I led my team in a game.": "jɛstɚdeɪ aɪ lɛd maɪ tim ɪn ə ɡeɪm",
  "I've led my team in a game.": "aɪv lɛd maɪ tim ɪn ə ɡeɪm",
  "My block tower leans to one side.": "maɪ blɑk taʊɚ linz tu wʌn saɪd",
  "Yesterday, I leaned toward my friend.": "jɛstɚdeɪ aɪ lind təwɔrd maɪ frɛnd",
  "I've leaned toward my friend.": "aɪv lind təwɔrd maɪ frɛnd",
  "A frog leaps over the puddle.": "ə frɑɡ lips oʊvɚ ðə pʌdəl",
  "Yesterday, I leaped over a puddle.": "jɛstɚdeɪ aɪ lɛpt oʊvɚ ə pʌdəl",
  "I've leaped over a puddle.": "aɪv lɛpt oʊvɚ ə pʌdəl",
  "I learn a new song at school.": "aɪ lɝn ə nu sɔŋ æt skul",
  "Yesterday, I learned a new song at school.": "jɛstɚdeɪ aɪ lɝnd ə nu sɔŋ æt skul",
  "I've learned a new song at school.": "aɪv lɝnd ə nu sɔŋ æt skul",
  "I leave my shoes by the door.": "aɪ liv maɪ ʃuz baɪ ðə dɔr",
  "Yesterday, I left my shoes by the door.": "jɛstɚdeɪ aɪ lɛft maɪ ʃuz baɪ ðə dɔr",
  "I've left my shoes by the door.": "aɪv lɛft maɪ ʃuz baɪ ðə dɔr",
  "I lend my friend a pencil.": "aɪ lɛnd maɪ frɛnd ə pɛnsəl",
  "Yesterday, I lent my friend a pencil.": "jɛstɚdeɪ aɪ lɛnt maɪ frɛnd ə pɛnsəl",
  "I've lent my friend a pencil.": "aɪv lɛnt maɪ frɛnd ə pɛnsəl",
  "I let my little brother play.": "aɪ lɛt maɪ lɪtəl brʌðɚ pleɪ",
  "Yesterday, I let my little brother play.": "jɛstɚdeɪ aɪ lɛt maɪ lɪtəl brʌðɚ pleɪ",
  "I've let my little brother play.": "aɪv lɛt maɪ lɪtəl brʌðɚ pleɪ",
  "I lie about breaking a crayon.": "aɪ laɪ əbaʊt breɪkɪŋ ə kreɪɑn",
  "Yesterday, I lied about breaking a crayon.": "jɛstɚdeɪ aɪ laɪd əbaʊt breɪkɪŋ ə kreɪɑn",
  "I've lied about breaking a crayon.": "aɪv laɪd əbaʊt breɪkɪŋ ə kreɪɑn",
  "I lie down for a nap.": "aɪ laɪ daʊn fɔr ə næp",
  "Yesterday, I lay down for a nap.": "jɛstɚdeɪ aɪ leɪ daʊn fɔr ə næp",
  "I've lain down for a nap.": "aɪv leɪn daʊn fɔr ə næp",
  "I light a candle on my birthday cake.": "aɪ laɪt ə kændəl ɑn maɪ bɝθdeɪ keɪk",
  "Yesterday, I lit a candle on my birthday cake.": "jɛstɚdeɪ aɪ lɪt ə kændəl ɑn maɪ bɝθdeɪ keɪk",
  "I've lit a candle on my birthday cake.": "aɪv lɪt ə kændəl ɑn maɪ bɝθdeɪ keɪk",
  "I lose my favorite glove.": "aɪ luz maɪ feɪvɚɪt ɡlʌv",
  "Yesterday, I lost my favorite glove.": "jɛstɚdeɪ aɪ lɔst maɪ feɪvɚɪt ɡlʌv",
  "I've lost my favorite glove.": "aɪv lɔst maɪ feɪvɚɪt ɡlʌv",
  "I make a card for my grandma.": "aɪ meɪk ə kɑrd fɔr maɪ ɡrændmɑ",
  "Yesterday, I made a card for my grandma.": "jɛstɚdeɪ aɪ meɪd ə kɑrd fɔr maɪ ɡrændmɑ",
  "I've made a card for my grandma.": "aɪv meɪd ə kɑrd fɔr maɪ ɡrændmɑ",
  "I mean what I say.": "aɪ min wʌt aɪ seɪ",
  "Yesterday, my teacher meant 'happy' when she said 'glad.'": "jɛstɚdeɪ maɪ titʃɚ mɛnt hæpi wɛn ʃi sɛd ɡlæd",
  "My teacher has meant well.": "maɪ titʃɚ hæz mɛnt wɛl",
  "I meet my friend at the park.": "aɪ mit maɪ frɛnd æt ðə pɑrk",
  "Yesterday, I met my friend at the park.": "jɛstɚdeɪ aɪ mɛt maɪ frɛnd æt ðə pɑrk",
  "I've met my friend at the park.": "aɪv mɛt maɪ frɛnd æt ðə pɑrk",
  "I mislay my library book.": "aɪ mɪsleɪ maɪ laɪbrɛri bʊk",
  "Yesterday, I mislaid my library book.": "jɛstɚdeɪ aɪ mɪsleɪd maɪ laɪbrɛri bʊk",
  "I've mislaid my library book.": "aɪv mɪsleɪd maɪ laɪbrɛri bʊk",
  "I mistake my friend for my cousin.": "aɪ mɪsteɪk maɪ frɛnd fɔr maɪ kʌzən",
  "Yesterday, I mistook my friend for my cousin.": "jɛstɚdeɪ aɪ mɪstʊk maɪ frɛnd fɔr maɪ kʌzən",
  "I've mistaken my friend for my cousin.": "aɪv mɪsteɪkən maɪ frɛnd fɔr maɪ kʌzən",
  "I overtake my dad on a walk.": "aɪ oʊvɚteɪk maɪ dæd ɑn ə wɔk",
  "Yesterday, I overtook my dad on a walk.": "jɛstɚdeɪ aɪ oʊvɚtʊk maɪ dæd ɑn ə wɔk",
  "I've overtaken my dad on a walk.": "aɪv oʊvɚteɪkən maɪ dæd ɑn ə wɔk",
  "I pay for a comic book.": "aɪ peɪ fɔr ə kɑmɪk bʊk",
  "Yesterday, I paid for a comic book.": "jɛstɚdeɪ aɪ peɪd fɔr ə kɑmɪk bʊk",
  "I've paid for a comic book.": "aɪv peɪd fɔr ə kɑmɪk bʊk",
  "I prove I can be brave.": "aɪ pruv aɪ kæn bi breɪv",
  "Yesterday, I proved I can be brave.": "jɛstɚdeɪ aɪ pruvd aɪ kæn bi breɪv",
  "I've proven I can be brave.": "aɪv pruvən aɪ kæn bi breɪv",
  "I put my toy on the shelf.": "aɪ pʊt maɪ tɔɪ ɑn ðə ʃɛlf",
  "Yesterday, I put my toy on the shelf.": "jɛstɚdeɪ aɪ pʊt maɪ tɔɪ ɑn ðə ʃɛlf",
  "I've put my toy on the shelf.": "aɪv pʊt maɪ tɔɪ ɑn ðə ʃɛlf",
  "I quit playing my game before dinner.": "aɪ kwɪt pleɪɪŋ maɪ ɡeɪm bɪfɔr dɪnɚ",
  "Yesterday, I quit playing my game before dinner.": "jɛstɚdeɪ aɪ kwɪt pleɪɪŋ maɪ ɡeɪm bɪfɔr dɪnɚ",
  "I've quit playing my game before dinner.": "aɪv kwɪt pleɪɪŋ maɪ ɡeɪm bɪfɔr dɪnɚ",
  "I read a book before bed.": "aɪ rɛd ə bʊk bɪfɔr bɛd",
  "Yesterday, I read a book before bed.": "jɛstɚdeɪ aɪ rɛd ə bʊk bɪfɔr bɛd",
  "I've read a book before bed.": "aɪv rɛd ə bʊk bɪfɔr bɛd",
  "I rid my room of old papers.": "aɪ rɪd maɪ rum ʌv oʊld peɪpɚz",
  "Yesterday, I rid my room of old papers.": "jɛstɚdeɪ aɪ rɪd maɪ rum ʌv oʊld peɪpɚz",
  "I've rid my room of old papers.": "aɪv rɪd maɪ rum ʌv oʊld peɪpɚz",
  "I ride my bike to school.": "aɪ raɪd maɪ baɪk tu skul",
  "Yesterday, I rode my bike to school.": "jɛstɚdeɪ aɪ roʊd maɪ baɪk tu skul",
  "I've ridden my bike to school.": "aɪv rɪdən maɪ baɪk tu skul",
  "The school bell rings for lunch.": "ðə skul bɛl rɪŋz fɔr lʌntʃ",
  "Yesterday, I rang the bell for lunch.": "jɛstɚdeɪ aɪ ræŋ ðə bɛl fɔr lʌntʃ",
  "I've rung the bell for lunch.": "aɪv rʌŋ ðə bɛl fɔr lʌntʃ",
  "The sun rises before I leave for school.": "ðə sʌn raɪzəz bɪfɔr aɪ liv fɔr skul",
  "Yesterday, I rose up early for school.": "jɛstɚdeɪ aɪ roʊz ʌp ɝli fɔr skul",
  "I've risen up early for school.": "aɪv rɪzən ʌp ɝli fɔr skul",
  "I run to the bus stop.": "aɪ rʌn tu ðə bʌs stɑp",
  "Yesterday, I ran to the bus stop.": "jɛstɚdeɪ aɪ ræn tu ðə bʌs stɑp",
  "I've run to the bus stop.": "aɪv rʌn tu ðə bʌs stɑp",
  "I saw a piece of wood in class.": "aɪ sɔ ə pis ʌv wʊd ɪn klæs",
  "Yesterday, I sawed a piece of wood in class.": "jɛstɚdeɪ aɪ sɔd ə pis ʌv wʊd ɪn klæs",
  "I've sawed a piece of wood in class.": "aɪv sɔd ə pis ʌv wʊd ɪn klæs",
  "I say thank you to my teacher.": "aɪ seɪ θæŋk ju tu maɪ titʃɚ",
  "Yesterday, I said thank you to my teacher.": "jɛstɚdeɪ aɪ sɛd θæŋk ju tu maɪ titʃɚ",
  "I've said thank you to my teacher.": "aɪv sɛd θæŋk ju tu maɪ titʃɚ",
  "I see a rainbow after the rain.": "aɪ si ə reɪnboʊ æftɚ ðə reɪn",
  "Yesterday, I saw a rainbow after the rain.": "jɛstɚdeɪ aɪ sɔ ə reɪnboʊ æftɚ ðə reɪn",
  "I've seen a rainbow after the rain.": "aɪv sin ə reɪnboʊ æftɚ ðə reɪn",
  "I seek my missing sock.": "aɪ sik maɪ mɪsɪŋ sɑk",
  "Yesterday, I sought my missing sock.": "jɛstɚdeɪ aɪ sɔt maɪ mɪsɪŋ sɑk",
  "I've sought my missing sock.": "aɪv sɔt maɪ mɪsɪŋ sɑk",
  "I sell lemonade at the school fair.": "aɪ sɛl lɛməneɪd æt ðə skul fɛr",
  "Yesterday, I sold lemonade at the school fair.": "jɛstɚdeɪ aɪ soʊld lɛməneɪd æt ðə skul fɛr",
  "I've sold lemonade at the school fair.": "aɪv soʊld lɛməneɪd æt ðə skul fɛr",
  "I send a card to my grandma.": "aɪ sɛnd ə kɑrd tu maɪ ɡrændmɑ",
  "Yesterday, I sent a card to my grandma.": "jɛstɚdeɪ aɪ sɛnt ə kɑrd tu maɪ ɡrændmɑ",
  "I've sent a card to my grandma.": "aɪv sɛnt ə kɑrd tu maɪ ɡrændmɑ",
  "I set the table for dinner.": "aɪ sɛt ðə teɪbəl fɔr dɪnɚ",
  "Yesterday, I set the table for dinner.": "jɛstɚdeɪ aɪ sɛt ðə teɪbəl fɔr dɪnɚ",
  "I've set the table for dinner.": "aɪv sɛt ðə teɪbəl fɔr dɪnɚ",
  "I sew a button on my shirt.": "aɪ soʊ ə bʌtən ɑn maɪ ʃɝt",
  "Yesterday, I sewed a button on my shirt.": "jɛstɚdeɪ aɪ soʊd ə bʌtən ɑn maɪ ʃɝt",
  "I've sewn a button on my shirt.": "aɪv soʊn ə bʌtən ɑn maɪ ʃɝt",
  "My dog shakes water from his fur.": "maɪ dɔɡ ʃeɪks wɔtɚ frʌm hɪz fɝ",
  "Yesterday, I shook the rain off my umbrella.": "jɛstɚdeɪ aɪ ʃʊk ðə reɪn ɔf maɪ əmbrɛlə",
  "I've shaken the rain off my umbrella.": "aɪv ʃeɪkən ðə reɪn ɔf maɪ əmbrɛlə",
  "I shave my doll's hair.": "aɪ ʃeɪv maɪ dɑlz hɛr",
  "Yesterday, I shaved my doll's hair.": "jɛstɚdeɪ aɪ ʃeɪvd maɪ dɑlz hɛr",
  "I've shaved my doll's hair.": "aɪv ʃeɪvd maɪ dɑlz hɛr",
  "I shear a sheep in a story.": "aɪ ʃɪr ə ʃip ɪn ə stɔri",
  "Yesterday, I sheared a sheep in a story.": "jɛstɚdeɪ aɪ ʃɪrd ə ʃip ɪn ə stɔri",
  "I've sheared a sheep in a story.": "aɪv ʃɪrd ə ʃip ɪn ə stɔri",
  "I shed my wet coat.": "aɪ ʃɛd maɪ wɛt koʊt",
  "Yesterday, I shed my wet coat.": "jɛstɚdeɪ aɪ ʃɛd maɪ wɛt koʊt",
  "I've shed my wet coat.": "aɪv ʃɛd maɪ wɛt koʊt",
  "My flashlight shines under the bed.": "maɪ flæʃlaɪt ʃaɪnz ʌndɚ ðə bɛd",
  "Yesterday, I shone my flashlight under the bed.": "jɛstɚdeɪ aɪ ʃoʊn maɪ flæʃlaɪt ʌndɚ ðə bɛd",
  "I've shone my flashlight under the bed.": "aɪv ʃoʊn maɪ flæʃlaɪt ʌndɚ ðə bɛd",
  "I shoot a basketball into the hoop.": "aɪ ʃut ə bæskətbɔl ɪntu ðə hup",
  "Yesterday, I shot a basketball into the hoop.": "jɛstɚdeɪ aɪ ʃɑt ə bæskətbɔl ɪntu ðə hup",
  "I've shot a basketball into the hoop.": "aɪv ʃɑt ə bæskətbɔl ɪntu ðə hup",
  "I show my drawing to my dad.": "aɪ ʃoʊ maɪ drɔɪŋ tu maɪ dæd",
  "Yesterday, I showed my drawing to my dad.": "jɛstɚdeɪ aɪ ʃoʊd maɪ drɔɪŋ tu maɪ dæd",
  "I've showed my drawing to my dad.": "aɪv ʃoʊd maɪ drɔɪŋ tu maɪ dæd",
  "My sweater shrinks in hot water.": "maɪ swɛtɚ ʃrɪŋks ɪn hɑt wɔtɚ",
  "Yesterday, I shrank my shirt in hot water.": "jɛstɚdeɪ aɪ ʃræŋk maɪ ʃɝt ɪn hɑt wɔtɚ",
  "I've shrunk my shirt in hot water.": "aɪv ʃrʌŋk maɪ ʃɝt ɪn hɑt wɔtɚ",
  "I shut the door quietly.": "aɪ ʃʌt ðə dɔr kwaɪətli",
  "Yesterday, I shut the door quietly.": "jɛstɚdeɪ aɪ ʃʌt ðə dɔr kwaɪətli",
  "I've shut the door quietly.": "aɪv ʃʌt ðə dɔr kwaɪətli",
  "Our class sings in music time.": "aʊɚ klæs sɪŋz ɪn mjuzɪk taɪm",
  "Yesterday, I sang a song in music class.": "jɛstɚdeɪ aɪ sæŋ ə sɔŋ ɪn mjuzɪk klæs",
  "I've sung a song in music class.": "aɪv sʌŋ ə sɔŋ ɪn mjuzɪk klæs",
  "My toy boat sinks in the bath.": "maɪ tɔɪ boʊt sɪŋks ɪn ðə bæθ",
  "Yesterday, my toy boat sank in the bath.": "jɛstɚdeɪ maɪ tɔɪ boʊt sæŋk ɪn ðə bæθ",
  "My toy boat has sunk in the bath.": "maɪ tɔɪ boʊt hæz sʌŋk ɪn ðə bæθ",
  "I sit beside my friend.": "aɪ sɪt bɪsaɪd maɪ frɛnd",
  "Yesterday, I sat beside my friend.": "jɛstɚdeɪ aɪ sæt bɪsaɪd maɪ frɛnd",
  "I've sat beside my friend.": "aɪv sæt bɪsaɪd maɪ frɛnd",
  "I slay a dragon in my game.": "aɪ sleɪ ə dræɡən ɪn maɪ ɡeɪm",
  "Yesterday, I slew a dragon in my game.": "jɛstɚdeɪ aɪ slu ə dræɡən ɪn maɪ ɡeɪm",
  "I've slain a dragon in my game.": "aɪv sleɪn ə dræɡən ɪn maɪ ɡeɪm",
  "I sleep in my cozy bed.": "aɪ slip ɪn maɪ koʊzi bɛd",
  "Yesterday, I slept in my cozy bed.": "jɛstɚdeɪ aɪ slɛpt ɪn maɪ koʊzi bɛd",
  "I've slept in my cozy bed.": "aɪv slɛpt ɪn maɪ koʊzi bɛd",
  "My toy car slides down the ramp.": "maɪ tɔɪ kɑr slaɪdz daʊn ðə ræmp",
  "Yesterday, I slid down the slide.": "jɛstɚdeɪ aɪ slɪd daʊn ðə slaɪd",
  "I've slid down the slide.": "aɪv slɪd daʊn ðə slaɪd",
  "I slit an orange for lunch.": "aɪ slɪt æn ɔrəndʒ fɔr lʌntʃ",
  "Yesterday, I slit an orange for lunch.": "jɛstɚdeɪ aɪ slɪt æn ɔrəndʒ fɔr lʌntʃ",
  "I've slit an orange for lunch.": "aɪv slɪt æn ɔrəndʒ fɔr lʌntʃ",
  "I smell cookies in the kitchen.": "aɪ smɛl kʊkiz ɪn ðə kɪtʃən",
  "Yesterday, I smelled cookies in the kitchen.": "jɛstɚdeɪ aɪ smɛld kʊkiz ɪn ðə kɪtʃən",
  "I've smelled cookies in the kitchen.": "aɪv smɛld kʊkiz ɪn ðə kɪtʃən",
  "I speak English with my teacher.": "aɪ spik ɪŋɡlɪʃ wɪð maɪ titʃɚ",
  "Yesterday, I spoke English with my teacher.": "jɛstɚdeɪ aɪ spoʊk ɪŋɡlɪʃ wɪð maɪ titʃɚ",
  "I've spoken English with my teacher.": "aɪv spoʊkən ɪŋɡlɪʃ wɪð maɪ titʃɚ",
  "I speed up on my scooter.": "aɪ spid ʌp ɑn maɪ skutɚ",
  "Yesterday, I sped up on my scooter.": "jɛstɚdeɪ aɪ spɛd ʌp ɑn maɪ skutɚ",
  "I've sped up on my scooter.": "aɪv spɛd ʌp ɑn maɪ skutɚ",
  "I spell my name correctly.": "aɪ spɛl maɪ neɪm kɚɛktli",
  "Yesterday, I spelled my name correctly.": "jɛstɚdeɪ aɪ spɛld maɪ neɪm kɚɛktli",
  "I've spelled my name correctly.": "aɪv spɛld maɪ neɪm kɚɛktli",
  "I spend my pocket money on a toy.": "aɪ spɛnd maɪ pɑkət mʌni ɑn ə tɔɪ",
  "Yesterday, I spent my pocket money on a toy.": "jɛstɚdeɪ aɪ spɛnt maɪ pɑkət mʌni ɑn ə tɔɪ",
  "I've spent my pocket money on a toy.": "aɪv spɛnt maɪ pɑkət mʌni ɑn ə tɔɪ",
  "I spill juice on the table.": "aɪ spɪl dʒus ɑn ðə teɪbəl",
  "Yesterday, I spilled juice on the table.": "jɛstɚdeɪ aɪ spɪld dʒus ɑn ðə teɪbəl",
  "I've spilled juice on the table.": "aɪv spɪld dʒus ɑn ðə teɪbəl",
  "A top spins on the floor.": "ə tɑp spɪnz ɑn ðə flɔr",
  "Yesterday, I spun a top on the floor.": "jɛstɚdeɪ aɪ spʌn ə tɑp ɑn ðə flɔr",
  "I've spun a top on the floor.": "aɪv spʌn ə tɑp ɑn ðə flɔr",
  "I spit out my toothpaste.": "aɪ spɪt aʊt maɪ tuθpeɪst",
  "Yesterday, I spit out my toothpaste.": "jɛstɚdeɪ aɪ spɪt aʊt maɪ tuθpeɪst",
  "I've spit out my toothpaste.": "aɪv spɪt aʊt maɪ tuθpeɪst",
  "I split a sandwich with my friend.": "aɪ splɪt ə sændwɪtʃ wɪð maɪ frɛnd",
  "Yesterday, I split a sandwich with my friend.": "jɛstɚdeɪ aɪ splɪt ə sændwɪtʃ wɪð maɪ frɛnd",
  "I've split a sandwich with my friend.": "aɪv splɪt ə sændwɪtʃ wɪð maɪ frɛnd",
  "I spoil my surprise for my mom.": "aɪ spɔɪl maɪ sɚpraɪz fɔr maɪ mɑm",
  "Yesterday, I spoiled my surprise for my mom.": "jɛstɚdeɪ aɪ spɔɪld maɪ sɚpraɪz fɔr maɪ mɑm",
  "I've spoiled my surprise for my mom.": "aɪv spɔɪld maɪ sɚpraɪz fɔr maɪ mɑm",
  "I spread jam on my toast.": "aɪ sprɛd dʒæm ɑn maɪ toʊst",
  "Yesterday, I spread jam on my toast.": "jɛstɚdeɪ aɪ sprɛd dʒæm ɑn maɪ toʊst",
  "I've spread jam on my toast.": "aɪv sprɛd dʒæm ɑn maɪ toʊst",
  "A frog springs into the pond.": "ə frɑɡ sprɪŋz ɪntu ðə pɑnd",
  "Yesterday, I sprang up when the bell rings.": "jɛstɚdeɪ aɪ spræŋ ʌp wɛn ðə bɛl rɪŋz",
  "I've sprung up when the bell rings.": "aɪv sprʌŋ ʌp wɛn ðə bɛl rɪŋz",
  "I stand in line at school.": "aɪ stænd ɪn laɪn æt skul",
  "Yesterday, I stood in line at school.": "jɛstɚdeɪ aɪ stʊd ɪn laɪn æt skul",
  "I've stood in line at school.": "aɪv stʊd ɪn laɪn æt skul",
  "A raccoon steals a cookie from the table.": "ə rækun stilz ə kʊki frʌm ðə teɪbəl",
  "Yesterday, I stole a cookie from the jar.": "jɛstɚdeɪ aɪ stoʊl ə kʊki frʌm ðə dʒɑr",
  "I've stolen a cookie from the jar.": "aɪv stoʊlən ə kʊki frʌm ðə dʒɑr",
  "I stick a star sticker on my book.": "aɪ stɪk ə stɑr stɪkɚ ɑn maɪ bʊk",
  "Yesterday, I stuck a star sticker on my book.": "jɛstɚdeɪ aɪ stʌk ə stɑr stɪkɚ ɑn maɪ bʊk",
  "I've stuck a star sticker on my book.": "aɪv stʌk ə stɑr stɪkɚ ɑn maɪ bʊk",
  "A bee stings my finger.": "ə bi stɪŋz maɪ fɪŋɡɚ",
  "Yesterday, I stung my finger on a thorn.": "jɛstɚdeɪ aɪ stʌŋ maɪ fɪŋɡɚ ɑn ə θɔrn",
  "I've stung my finger on a thorn.": "aɪv stʌŋ maɪ fɪŋɡɚ ɑn ə θɔrn",
  "Wet socks stink after a rainy day.": "wɛt sɑks stɪŋk æftɚ ə reɪni deɪ",
  "Yesterday, I stank after wearing wet socks.": "jɛstɚdeɪ aɪ stæŋk æftɚ wɛrɪŋ wɛt sɑks",
  "I've stunk after wearing wet socks.": "aɪv stʌŋk æftɚ wɛrɪŋ wɛt sɑks",
  "I strike a drum in music class.": "aɪ straɪk ə drʌm ɪn mjuzɪk klæs",
  "Yesterday, I struck a drum in music class.": "jɛstɚdeɪ aɪ strʌk ə drʌm ɪn mjuzɪk klæs",
  "I've struck a drum in music class.": "aɪv strʌk ə drʌm ɪn mjuzɪk klæs",
  "I string beads for a bracelet.": "aɪ strɪŋ bidz fɔr ə breɪslət",
  "Yesterday, I strung beads for a bracelet.": "jɛstɚdeɪ aɪ strʌŋ bidz fɔr ə breɪslət",
  "I've strung beads for a bracelet.": "aɪv strʌŋ bidz fɔr ə breɪslət",
  "I strive to do my best.": "aɪ straɪv tu du maɪ bɛst",
  "Yesterday, I strove to do my best.": "jɛstɚdeɪ aɪ stroʊv tu du maɪ bɛst",
  "I've striven to do my best.": "aɪv strɪvən tu du maɪ bɛst",
  "I swear to tell the truth.": "aɪ swɛr tu tɛl ðə truθ",
  "Yesterday, I swore to tell the truth.": "jɛstɚdeɪ aɪ swɔr tu tɛl ðə truθ",
  "I've sworn to tell the truth.": "aɪv swɔrn tu tɛl ðə truθ",
  "I sweep the kitchen floor.": "aɪ swip ðə kɪtʃən flɔr",
  "Yesterday, I swept the kitchen floor.": "jɛstɚdeɪ aɪ swɛpt ðə kɪtʃən flɔr",
  "I've swept the kitchen floor.": "aɪv swɛpt ðə kɪtʃən flɔr",
  "My ankle swells after a bee sting.": "maɪ æŋkəl swɛlz æftɚ ə bi stɪŋ",
  "My ankle swelled after a bee sting.": "maɪ æŋkəl swɛld æftɚ ə bi stɪŋ",
  "My ankle has swollen since the bee sting.": "maɪ æŋkəl hæz swoʊlən sɪns ðə bi stɪŋ",
  "I swim in the pool.": "aɪ swɪm ɪn ðə pul",
  "Yesterday, I swam in the pool.": "jɛstɚdeɪ aɪ swæm ɪn ðə pul",
  "I've swum in the pool.": "aɪv swʌm ɪn ðə pul",
  "The swing swings at the playground.": "ðə swɪŋ swɪŋz æt ðə pleɪɡraʊnd",
  "Yesterday, I swung on the swings.": "jɛstɚdeɪ aɪ swʌŋ ɑn ðə swɪŋz",
  "I've swung on the swings.": "aɪv swʌŋ ɑn ðə swɪŋz",
  "I take my lunch to school.": "aɪ teɪk maɪ lʌntʃ tu skul",
  "Yesterday, I took my lunch to school.": "jɛstɚdeɪ aɪ tʊk maɪ lʌntʃ tu skul",
  "I've taken my lunch to school.": "aɪv teɪkən maɪ lʌntʃ tu skul",
  "I teach my friend a card game.": "aɪ titʃ maɪ frɛnd ə kɑrd ɡeɪm",
  "Yesterday, I taught my friend a card game.": "jɛstɚdeɪ aɪ tɔt maɪ frɛnd ə kɑrd ɡeɪm",
  "I've taught my friend a card game.": "aɪv tɔt maɪ frɛnd ə kɑrd ɡeɪm",
  "I tear paper for my craft.": "aɪ tɛr peɪpɚ fɔr maɪ kræft",
  "Yesterday, I tore paper for my craft.": "jɛstɚdeɪ aɪ tɔr peɪpɚ fɔr maɪ kræft",
  "I've torn paper for my craft.": "aɪv tɔrn peɪpɚ fɔr maɪ kræft",
  "I tell my mom about school.": "aɪ tɛl maɪ mɑm əbaʊt skul",
  "Yesterday, I told my mom about school.": "jɛstɚdeɪ aɪ toʊld maɪ mɑm əbaʊt skul",
  "I've told my mom about school.": "aɪv toʊld maɪ mɑm əbaʊt skul",
  "I think about my next drawing.": "aɪ θɪŋk əbaʊt maɪ nɛkst drɔɪŋ",
  "Yesterday, I thought about my next drawing.": "jɛstɚdeɪ aɪ θɔt əbaʊt maɪ nɛkst drɔɪŋ",
  "I've thought about my next drawing.": "aɪv θɔt əbaʊt maɪ nɛkst drɔɪŋ",
  "I throw a ball to my dog.": "aɪ θroʊ ə bɔl tu maɪ dɔɡ",
  "Yesterday, I threw a ball to my dog.": "jɛstɚdeɪ aɪ θru ə bɔl tu maɪ dɔɡ",
  "I've thrown a ball to my dog.": "aɪv θroʊn ə bɔl tu maɪ dɔɡ",
  "I thrust my toy sword forward.": "aɪ θrʌst maɪ tɔɪ sɔrd fɔrwɚd",
  "Yesterday, I thrust my toy sword forward.": "jɛstɚdeɪ aɪ θrʌst maɪ tɔɪ sɔrd fɔrwɚd",
  "I've thrust my toy sword forward.": "aɪv θrʌst maɪ tɔɪ sɔrd fɔrwɚd",
  "I undergo a checkup at school.": "aɪ ʌndɚɡoʊ ə tʃɛkʌp æt skul",
  "Yesterday, I underwent a checkup at school.": "jɛstɚdeɪ aɪ ʌndɚwɛnt ə tʃɛkʌp æt skul",
  "I've undergone a checkup at school.": "aɪv ʌndɚɡɔn ə tʃɛkʌp æt skul",
  "I understand my teacher's question.": "aɪ ʌndɚstænd maɪ titʃɚz kwɛstʃən",
  "Yesterday, I understood my teacher's question.": "jɛstɚdeɪ aɪ ʌndɚstʊd maɪ titʃɚz kwɛstʃən",
  "I've understood my teacher's question.": "aɪv ʌndɚstʊd maɪ titʃɚz kwɛstʃən",
  "I undertake a big art project.": "aɪ ʌndɚteɪk ə bɪɡ ɑrt prɑdʒɛkt",
  "Yesterday, I undertook a big art project.": "jɛstɚdeɪ aɪ ʌndɚtʊk ə bɪɡ ɑrt prɑdʒɛkt",
  "I've undertaken a big art project.": "aɪv ʌndɚteɪkən ə bɪɡ ɑrt prɑdʒɛkt",
  "I upset my cup of water.": "aɪ əpsɛt maɪ kʌp ʌv wɔtɚ",
  "Yesterday, I upset my cup of water.": "jɛstɚdeɪ aɪ əpsɛt maɪ kʌp ʌv wɔtɚ",
  "I've upset my cup of water.": "aɪv əpsɛt maɪ kʌp ʌv wɔtɚ",
  "I wake up before school.": "aɪ weɪk ʌp bɪfɔr skul",
  "Yesterday, I woke up before school.": "jɛstɚdeɪ aɪ woʊk ʌp bɪfɔr skul",
  "I've woken up before school.": "aɪv woʊkən ʌp bɪfɔr skul",
  "I wear my warm coat.": "aɪ wɛr maɪ wɔrm koʊt",
  "Yesterday, I wore my warm coat.": "jɛstɚdeɪ aɪ wɔr maɪ wɔrm koʊt",
  "I've worn my warm coat.": "aɪv wɔrn maɪ wɔrm koʊt",
  "I weave a paper basket.": "aɪ wiv ə peɪpɚ bæskət",
  "Yesterday, I wove a paper basket.": "jɛstɚdeɪ aɪ woʊv ə peɪpɚ bæskət",
  "I've woven a paper basket.": "aɪv woʊvən ə peɪpɚ bæskət",
  "I weep when my balloon pops.": "aɪ wip wɛn maɪ bəlun pɑps",
  "Yesterday, I wept when my balloon pops.": "jɛstɚdeɪ aɪ wɛpt wɛn maɪ bəlun pɑps",
  "I've wept when my balloon pops.": "aɪv wɛpt wɛn maɪ bəlun pɑps",
  "I wet my hands at the sink.": "aɪ wɛt maɪ hændz æt ðə sɪŋk",
  "Yesterday, I wetted my hands at the sink.": "jɛstɚdeɪ aɪ wɛtɪd maɪ hændz æt ðə sɪŋk",
  "I've wetted my hands at the sink.": "aɪv wɛtɪd maɪ hændz æt ðə sɪŋk",
  "I win a ribbon in the race.": "aɪ wɪn ə rɪbən ɪn ðə reɪs",
  "Yesterday, I won a ribbon in the race.": "jɛstɚdeɪ aɪ wʌn ə rɪbən ɪn ðə reɪs",
  "I've won a ribbon in the race.": "aɪv wʌn ə rɪbən ɪn ðə reɪs",
  "I wind my toy car key.": "aɪ waɪnd maɪ tɔɪ kɑr ki",
  "Yesterday, I wound my toy car key.": "jɛstɚdeɪ aɪ waʊnd maɪ tɔɪ kɑr ki",
  "I've wound my toy car key.": "aɪv waʊnd maɪ tɔɪ kɑr ki",
  "I withdraw my hand from the hot cup.": "aɪ wɪðdrɔ maɪ hænd frʌm ðə hɑt kʌp",
  "Yesterday, I withdrew my hand from the hot cup.": "jɛstɚdeɪ aɪ wɪθdru maɪ hænd frʌm ðə hɑt kʌp",
  "I've withdrawn my hand from the hot cup.": "aɪv wɪθdrɔn maɪ hænd frʌm ðə hɑt kʌp",
  "I wring water from my towel.": "aɪ rɪŋ wɔtɚ frʌm maɪ taʊəl",
  "Yesterday, I wrung water from my towel.": "jɛstɚdeɪ aɪ rʌŋ wɔtɚ frʌm maɪ taʊəl",
  "I've wrung water from my towel.": "aɪv rʌŋ wɔtɚ frʌm maɪ taʊəl",
  "I write a note to my friend.": "aɪ raɪt ə noʊt tu maɪ frɛnd",
  "Yesterday, I wrote a note to my friend.": "jɛstɚdeɪ aɪ roʊt ə noʊt tu maɪ frɛnd",
  "I've written a note to my friend.": "aɪv rɪtən ə noʊt tu maɪ frɛnd"
};

function ipaForSentence(sentence) {
  return SENTENCE_IPA[sentence] || '';
}
